build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs"
  contactDetails:
    name: "yesenia - Product Owner"
    email: "yesenia@gmail.com"
  onCallSupport:
    - 990449496
    - 990449496