build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs"
  contactDetails:
    name: "angel - QA Lead"
    email: "angel@gmail.com"
  onCallSupport:
    - 980449496
    - 980449496