build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs"
  contactDetails:
    name: "gio - QA Lead"
    email: "gio@gmail.com"
  onCallSupport:
    - 980449496
    - 980449496