build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Joel - Developer"
    email: "joel@gmail.com"
  onCallSupport:
    - 970449496
    - 970449496