build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related prod APIs"
  contactDetails:
    name: "gladys - Product Owner"
    email: "gladys@gmail.com"
  onCallSupport:
    - 990449496
    - 990449496