spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          # search-locations: "file:///C://Dev//Projects//Microservices//Documents//config"
        git:
          uri: "https://github.com/MiguelJarecca/easybank-config.git"
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071
